### ISSUE TITLE
Upload to Hackage?

### ISSUE THREAD

**Issue by Gabriella439** [wyager/FastPush#1]
Would you be able to upload the latest `FastPush` to Hackage?

This is not urgent, but it will fix a `nixpkgs` build failure since `nixpkgs` by default tries to build this library against the latest version of `STMonadTrans` (currently `0.4.3`) and the latest version of `FastPush` on Hackage has an upper bound of `STMonadTrans < 0.4`

**Comment by wyager** [comment]
Yep, on it.

**Comment by wyager** [comment]
OK, uploaded. I'm on slow coffee shop wifi, so I haven't actually tested with latest STMonadTrans yet, but I'll fix it if that doesn't work for some reason.

**Comment by wyager** [comment]
OK, cool. I get a deprecation warning, but that's because I want to keep supporting STMonadTrans 0.3.x for at least a little while. Eventually I'll remove 0.3.x compatibility.

**Comment by Gabriella439** [comment]
Thank you!
